version: "3.8"
services:
  backend:
    image: "abdallasarhan/springboot-react-fullstack:27.8.2022.19.37.40"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev